export const
  products = [{
    img: 'sanfran.jpg',
    name: "San Francisco",
    price: 990,
    alt: "Image by Free-Photos from Pixabay",
    qtty: 0,
    desc: "There may not be a Heaven, but there is San Francisco.",
    descname: "Ashleigh Brilliant",
    author: "February 20, 2020 by David",
    info: "San Francisco, officially the City and County of San Francisco and colloquially known as SF, San Fran, Frisco, or The City, is the cultural, commercial, and financial center of Northern California.",
    high: "You might have heard that San Francisco has a wild streak a mile wide, but it also happens to be 4.5 miles long. Golden Gate Park lets San Franciscans tap-dance with penguins at California Academy of Sciences, pull Oceanic mask faces at MH de Young Museum, and squeal over the teensy bonsai forest in the Japanese Tea Garden. It’s hard to believe these 1017 acres of lush terrain were once just scrubby sand dunes, and that San Franciscans have successfully preserved this stretch of green since 1866, ousting casinos and a theme-park igloo village. Today, everything San Francisco really needs is here: inspiration, nature and microbrewed beer at the Beach Chalet.",
    highheading: "Golden Gate Park",
    id: 0,
    start: "12.03.2020",
    dur: "9"
  },{
    img: 'mallorca-cala.jpg',
    name: "Mallorca - Cala",
    price: 1200,
    alt: "Image by mruizdeassin from Pixabay",
    qtty: 0,
    desc: "Majorca is a paradise, if you can stand it.",
    descname: "Gertrude Stein",
    author: "February 08, 2020 by David",
    info: "Mallorca (Majorca) is one of Spain's Balearic Islands in the Mediterranean. It's known for beach resorts, sheltered coves, limestone mountains and Roman and Moorish remains. Capital Palma has nightlife, the Moorish Almudaina royal palace and 13th-century Santa María Cathedral. Stone-built villages include Pollença, with its art galleries and music festival, and hillside Fornalutx, surrounded by citrus plantations.",
    high: "Mallorca is home to many species of dolphins and they can often be found swimming alongside boats. School groups can embark on a dolphin watching boat ride and learn more about the local pods.",
    highheading: "Mallorca’s friendliest residents",
    id: 1,
    start: "15.03.2020",
    dur: "9"
  },{
    img: "indo.jpg",
    name: "Indonesia - Tumpak Sewu",
    price: 700,
    alt: "Image by iqbal nuril anwar from Pixabay",
    qtty: 0,
    desc: "Water is the most perfect traveller because when it travels it becomes the path itself!",
    descname: "Mehmet Murat ildan",
    author: "January 10, 2020 by David",
    info: "Tumpak Sewu, also known as Coban Sewu, is a tiered waterfall that is located between the Pronojiwo District, Lumajang Regency, and the Ampelgading District, Malang Regency, in East Java, Indonesia. The waterfall is overshadowed by Semeru, an active volcano and the highest mountain in Java. The Glidik River is a meltwater source fed from the mountain, which is the primary flow for the waterfall. Tumpak Sewu is loosely translated to mean 'a thousand waterfalls' in the Javanese language. The name likely originated due to its appearance of many different waterfalls in one single, semi-circular area.",
    high: "",
    highheading: "Waterfalls",
    id: 2,
    start: "14.03.2020",
    dur: "6"
  },{
    img: "salzburg.jpg",
    name: "Salzburg",
    price: 120,
    alt: "Image by Zéno Tóth from Pixabay",
    qtty: 0,
    desc: "One large demanding fortress with an alpine backdrop sets Salzburg apart from other cities, attracting more and more tourists every year.",
    descname: "Lust for the World",
    author: "January 20, 2020 by David",
    info: "Salzburg is an Austrian city on the border of Germany, with views of the Eastern Alps. The city is divided by the Salzach River, with medieval and baroque buildings of the pedestrian Altstadt (Old City) on its left bank, facing the 19th-century Neustadt (New City) on its right. The Altstadt birthplace of famed composer Mozart is preserved as a museum displaying his childhood instruments.",
    high: "Hangar-7 is a building in Salzburg, Austria, hosting a collection of historical airplanes, helicopters and Formula One racing cars, and serving as home for the Flying Bulls, a private aircraft fleet stationed in Salzburg. Hangar-7 is owned by Red Bull founder Dietrich Mateschitz.",
    highheading: "Red Bull Hangar-7",
    id: 3,
    start: "12.03.2020",
    dur: "7"
  },{
    img: "london.jpg",
    name: "London",
    price: 300,
    alt: "Image by E.Dichtl from Pixabay",
    qtty: 0,
    desc: "I travel continuously, and I see many cities, but there is nowhere like London.",
    descname: "Norman Foster",
    author: "February 19, 2020 by David",
    info: "London, the capital of England and the United Kingdom, is a 21st-century city with history stretching back to Roman times. At its centre stand the imposing Houses of Parliament, the iconic ‘Big Ben’ clock tower and Westminster Abbey, site of British monarch coronations. Across the Thames River, the London Eye observation wheel provides panoramic views of the South Bank cultural complex, and the entire city.",
    high: "The very popular ferris wheel is located at the south bank of the river Thames beside a small park, the Jubilee Gardens. Nearby you can find the Golden Jubilee Bridge. This pedestrian bridge across the Thames offers a good view at the London Eye and the surroundings.",
    highheading: "London Eye",
    id: 4,
    start: "07.03.2020",
    dur: "12"
  },{
    img: "tokyo.jpg",
    name: "Tokyo",
    price: 1100,
    alt: "Image by Walkerssk from Pixabay",
    qtty: 0,
    desc: "Tokyo would probably be the foreign city if I had to eat one city’s food for the rest of my life, every day. It would have to be Tokyo, and I think the majority of chefs you ask that question would answer the same way.",
    descname: "Anthony Bourdain",
    author: "February 18, 2020 by David",
    info: "Tokyo is a major cultural hub and an international trendsetter in the arts, entertainment, gastronomy, and media.",
    high: "Shinjuku is the biggest nightlife district in the land of the rising neon sun. There is truly something for everyone here, from the anachronistic shanty bars of Golden Gai, a favourite haunt of writers and artists; to the camp dance bars of Tokyo's gay quarter, Shinjuku-nichōme; and to the old-school izakaya (Japanese pub-eateries) of Shinjuku-sanchōme, where co-workers go to unwind after work. There are all-night karaoke parlours, jazz dens and hipster cocktail bars. The options are dizzying, the lights spellbinding and the whole show continues past dawn.",
    highheading: "Shinjuku",
    id: 5,
    start: "01.03.2020",
    dur: "10"
  }
  ];
